version: '3'
services :
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mess
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080